name: Linting
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NF_CORE_TOOLS_VERSION: "3.2.1"

jobs:
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install NodeJS
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4.4.0

      - name: Install Prettier
        run: npm install -g prettier

      - name: Run Prettier --check
        run: prettier --check .

  nf-core-modules:
    name: "nf-core Modules"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@505e6394dae86d6a5c7fbb6e3fb8938e3e863830 # v3.1.1
        with:
          miniforge-version: latest
          conda-remove-defaults: true
          activate-environment: "nf-core-tools"

      - name: Install nf-core tools
        run: conda install -c bioconda nf-core=${{ env.NF_CORE_TOOLS_VERSION }}

      - name: Lint nf-core modules
        run: nf-core --hide-progress modules lint --all

      - name: Lint nf-core subworkflows
        run: nf-core --hide-progress subworkflows lint --all
