name: Linting
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lints:
    runs-on: ubuntu-latest
    defaults:
      run:
        # required for Conda
        shell: bash -el {0}
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cache Conda packages
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/conda_pkgs_dir
          key: conda-pkgs_${{ runner.os }}_${{ hashFiles('environment-dev.conda.linux-64.lock') }}

      - name: Set up development environment
        uses: conda-incubator/setup-miniconda@505e6394dae86d6a5c7fbb6e3fb8938e3e863830 # v3.1.1
        with:
          miniforge-version: latest
          conda-remove-defaults: "true"
          environment-file: environment-dev.conda.linux-64.lock
          use-only-tar-bz2: true # required for proper caching

      - name: Check Prettier formatting
        run: prettier --check .

      - name: Check Python script formatting
        run: ruff format --check bin/

      - name: Lint Python scripts
        run: ruff check --extend-select I

      - name: Lint and check formatting of local Nextflow scripts
        run: |
          find main.nf workflows/ subworkflows/local modules/local \
          -exec nextflow lint -format -sort-declarations -harshil-alignment {} + \
          | (! grep 'formatted') \
          || (echo 'Some Nextflow scripts were not formatted properly!' && exit 1)

      - name: Lint nf-core modules
        run: nf-core --hide-progress modules lint --all

      - name: Lint nf-core subworkflows
        run: nf-core --hide-progress subworkflows lint --all
